version: '3.9'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    ports: 
      - "3000:3000"
    volumes:
      - .:/concurrency-control-api
      - gem_cache:/usr/local/bundle/gems
    env_file: .env.docker

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file: .env.docker
    command: postgres -c 'max_connections=300'
    ports:
      - 5432:5432

  redis:
    image: redis
    ports:
      - 6379:6379


volumes:
  gem_cache:
  db_data: